apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-deti-power.fullname" . }}-config
  labels:
    {{- include "wasp-deti-power.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  waspSensor: {{ .Values.config.waspSensorType }}
  logLevel: {{ .Values.config.logLevel }}
  kafkaLogLevel: {{ .Values.config.kafkajsLogLevel }}
  kafkaBrokers: {{ include "wasp-deti-power.kafka.brokers" . }}
  kafkaReadingsTopic: {{ .Values.config.kafkaReadingsTopic }}
  kafkaPayloadRoutingPrefix: {{ .Values.config.kafkaPayloadRoutingPrefix }}
  kafkaPayloadsPartitions: {{ .Values.config.kafkaPayloadsPartitions | quote }}
  kafkaPayloadsReplicationFactor: {{ .Values.config.kafkaPayloadsReplicationFactor | quote }}
