waspthingmock:
  enabled: false
kafka:
  enabled: true
config:
  port: 80
  waspSensorType: detiPower
  logLevel: info
  kafkajsLogLevel: nothing

  # used if kafka is not deployed by this chart
  kafkaBrokers: null
  # kafka topic configuration
  kafkaReadingsTopic: readings
  kafkaPayloadRoutingPrefix: payloads
  kafkaPayloadsReplicationFactor: 1
  kafkaPayloadsPartitions: 5
  init:
    registerThingType: true
    thingServiceName: wasp-thing-service
    thingServicePort: 80
image:
  repository: ghcr.io/digicatapult/wasp-deti-power
  pullPolicy: IfNotPresent
  tag: 'v0.0.5'
  pullSecrets: ['ghcr-digicatapult']
